### ISSUE TITLE
No encuentro PDFs documentacion

### ISSUE THREAD

**Issue by jmaudes** [apm1005/TFG#78]
Hola Adrian
Seguramente es que estoy muy torpe, pero no veo la memoria ni los anexos. Donde los tienes?, normalmente cualgan de la carpeta documantacion
Jesus Maudes

**Comment by apm1005** [comment]
Hola Jesús!

Dentro del repositorio no he incluido ni memoria ni anexos, tan solo están los diagramas. No sabía que era necesario. ¿Debo incluirlos?

Un saludo!
________________________________

**Comment by jmaudes** [comment]
Quizas no, pero es lo habitual
Dejame que pregunte al presidente del tribunal como puedo consultarla si no
esta en git

Jesus

**Comment by jmaudes** [comment]
Vale, no hagas nada
Es culpa mia no conocia el procedimiento bien
Tampoco habia usado nunca tareas Turnitin
Ya lo he encontrado

Gracias


Jesus
